theme = "system"

[widgets]
displayed = [
    "default.spaces",
    "default.bluetooth"
]

[zonedLayout]
left = ["default.spaces"]
center = []
right = ["default.bluetooth"]

[background]
enabled = false

[yabai]
path = "/opt/homebrew/bin/yabai"

[aerospace]
path = "/opt/homebrew/bin/aerospace"
