id = "conductor-log"
name = "Conductor LOG"
schema_version = 1
version = "0.1.0"
authors = ["jow"]
description = "Log file syntax highlighting tuned for the Conductor theme."

[grammars.log]
repository = "https://github.com/Tudyx/tree-sitter-log"
commit = "62cfe307e942af3417171243b599cc7deac5eab9"
